<?php

namespace App\BasePageBundle\Repository;

use Doctrine\ORM\EntityRepository;
use App\AppBundle\Helper\Filters\IdFilter;
use App\AppBundle\Helper\AbstractRepository;

/**
 * BasePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasePageRepository extends AbstractRepository {
    
}
